### ISSUE TITLE
optimize:期望PROXY配置项改为非必填

### ISSUE THREAD

**Issue by zym27187** [zhaomaoniu/nonebot-plugin-steam-info#12]
因为运行环境的本地网关上已经做了proxy处理，不希望在项目配置上进行重复代理

**Comment by zhaomaoniu** [comment]
proxy为选填项，.env文件中可以不写

**Comment by zhaomaoniu** [comment]
对不起，我写的确实是必填

**Comment by zhaomaoniu** [comment]
已修改 PROXY 到选填项，请将插件更新至 [v1.0.1](https://github.com/zhaomaoniu/nonebot-plugin-steam-info/releases/tag/v1.0.1)

**Comment by zym27187** [comment]
感谢

**Comment by zym27187** [comment]
貌似处理上还有点问题，我手动将proxy相关的代码删除掉了，aiohttp可以正常连接了

**Comment by zhaomaoniu** [comment]
看不出来问题，我明天再测

**Comment by zhaomaoniu** [comment]
我测试不出来任何问题，如果可以的话，麻烦你给出 "貌似处理上还有点问题" 的相关报错

**Comment by zym27187** [comment]
```
nonebot | Error when running WebSocketConnection hook. Running cancelled!
Traceback (most recent call last):
File "C:\DunbaoNb2Bot\DunbaoNb2\bot.py", line 34, in <module>
nonebot.run()
File "C:\Users\Administrator.virtualenvs\DunbaoNb2Bot\Lib\site-packages\nonebot_init_.py", line 335, in run
get_driver().run(*args, **kwargs)
File "C:\Users\Administrator.virtualenvs\DunbaoNb2Bot\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
uvicorn.run(
File "C:\Users\Administrator.virtualenvs\DunbaoNb2Bot\Lib\site-packages\uvicorn\main.py", line 578, in run
server.run()
File "C:\Users\Administrator.virtualenvs\DunbaoNb2Bot\Lib\site-packages\uvicorn\server.py", line 61, in run
return asyncio.run(self.serve(sockets=sockets))
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
return runner.run(main)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
return self._loop.run_until_complete(task)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
self.run_forever()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
super().run_forever()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
self._run_once()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
handle._run()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
self._context.run(self._callback, *self._args)

File "C:\Users\Administrator.virtualenvs\DunbaoNb2Bot\Lib\site-packages\nonebot\internal\driver\abstract.py", line 168, in run_hook
await asyncio.gather(*coros)
File "C:\Users\Administrator.virtualenvs\DunbaoNb2Bot\Lib\site-packages\nonebot\utils.py", line 236, in run_coro_with_catch
return await coro
File "C:\Users\Administrator.virtualenvs\DunbaoNb2Bot\Lib\site-packages\nonebot\dependencies_init.py", line 94, in call
return await cast(Callable[..., Awaitable[R]], self.call)(**values)
File "C:\Users\Administrator.virtualenvs\DunbaoNb2Bot\Lib\site-packages\nonebot_plugin_steam_info_init_.py", line 194, in update_steam_info
steam_info = await get_steam_users_info(
File "C:\Users\Administrator.virtualenvs\DunbaoNb2Bot\Lib\site-packages\nonebot_plugin_steam_info\steam.py", line 43, in get_steam_users_info
async with session.get(
File "C:\Users\Administrator.virtualenvs\DunbaoNb2Bot\Lib\site-packages\aiohttp\client.py", line 1194, in aenter
self._resp = await self._coro
File "C:\Users\Administrator.virtualenvs\DunbaoNb2Bot\Lib\site-packages\aiohttp\client.py", line 605, in _request
await resp.start(conn)
File "C:\Users\Administrator.virtualenvs\DunbaoNb2Bot\Lib\site-packages\aiohttp\client_reqrep.py", line 966, in start
message, payload = await protocol.read() # type: ignore[union-attr]
File "C:\Users\Administrator.virtualenvs\DunbaoNb2Bot\Lib\site-packages\aiohttp\streams.py", line 622, in read
await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```
这是我昨晚的报错日志内容，具体操作就是PROXY配置项未填写时，aiohttp报错无法连接，在你发布v1.0.1后还是同样的问题，最后我将proxy相关的代码删除后，aiohttp可以正常连接了

**Comment by zym27187** [comment]
补充删除操作：我全局搜索proxy，对proxy关键字和相关传参进行了删除，目前没有发现有其他功能点受到影响
