### ISSUE TITLE
设置群聊头像以及昵称没有反应

### ISSUE THREAD

**Issue by YRRLYB** [zhaomaoniu/nonebot-plugin-steam-info#15]
07-17 19:05:24 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_steam_info, lineno=58) running complete
07-17 19:05:24 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_steam_info, lineno=58) failed.
Traceback (most recent call last):
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\aiohttp\connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "D:\bot\python\lib\asyncio\base_events.py", line 1103, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "D:\bot\python\lib\asyncio\base_events.py", line 1133, in _create_connection_transport
    await waiter
  File "D:\bot\python\lib\asyncio\sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "D:\bot\python\lib\asyncio\sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "D:\bot\python\lib\ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\bot\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\bot\python\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\bot\python\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\bot\python\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\bot\python\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\bot\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot_plugin_steam_info\__init__.py", line 348, in update_parent_info_handle
    info["avatar"] = PILImage.open(BytesIO(await to_image_data(seg)))
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot_plugin_steam_info\__init__.py", line 112, in to_image_data
    async with session.get(image.url) as resp:
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
    self._resp = await self._coro
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\aiohttp\connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\aiohttp\connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\aiohttp\connector.py", line 1029, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host multimedia.nt.qq.com.cn:443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1007)]
这是后台进程

**Comment by YRRLYB** [comment]
啥啥啥

**Comment by zhaomaoniu** [comment]
没有过llob，你得给我点时间我有空了复现下

**Comment by YRRLYB** [comment]
麻烦大佬了🙏🏻

**Comment by zhaomaoniu** [comment]
你用的是腾讯云吗

**Comment by YRRLYB** [comment]
不是，我弄得本地

**Comment by zhaomaoniu** [comment]
请尝试更新到最新版后重试

**Comment by YRRLYB** [comment]
okok感谢大佬
