### ISSUE TITLE
NameError: name 'old_players_dict' is not defined

### ISSUE THREAD

**Issue by haha-dream** [zhaomaoniu/nonebot-plugin-steam-info#16]
初次运行插件时报错

Nonebot 版本: `2.3.2`
插件版本: `1.2.1`

报错信息:
```
07-19 19:57:22 [ERROR] apscheduler | Job "fetch_and_broadcast_steam_info (trigger: interval[0:05:00], next run at: 2024-07-19 20:02:21 CST)" raised an exception
Traceback (most recent call last):
  File "D:\KoishiDiceBot\Koishi-gocq\Koishi-New\bot.py", line 15, in <module>
    nonebot.run()
  File "D:\KoishiDiceBot\Koishi-gocq\Koishi-New\.venv\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "D:\KoishiDiceBot\Koishi-gocq\Koishi-New\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\KoishiDiceBot\Koishi-gocq\Koishi-New\.venv\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "D:\KoishiDiceBot\Koishi-gocq\Koishi-New\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Komei\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Komei\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Komei\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Users\Komei\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Komei\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Users\Komei\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Users\Komei\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
> File "D:\KoishiDiceBot\Koishi-gocq\Koishi-New\.venv\Lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "D:\KoishiDiceBot\Koishi-gocq\Koishi-New\.venv\Lib\site-packages\nonebot_plugin_steam_info\__init__.py", line 231, in fetch_and_broadcast_steam_info
    old_players = old_players_dict[parent_id]
NameError: name 'old_players_dict' is not defined
```

**Comment by zhaomaoniu** [comment]
本人修改插件后未充分测试，直接发版，导致了这个bug

请将插件升级到 v1.2.2 后重试
