### ISSUE TITLE
改不了昵称 也不能改头像

### ISSUE THREAD

**Issue by nodesire7** [zhaomaoniu/nonebot-plugin-steam-info#17]
![image](https://github.com/user-attachments/assets/1aba9e8f-3f1e-4d79-9fdd-7dbf82de6055)
![image](https://github.com/user-attachments/assets/2c621bdc-66d3-44f9-bfa6-d316a5a63e79)
如图，报错ssl.c922
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host multimedia.nt.qq.com.cn:443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:992)]

07-31 10:34:24 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_steam_info, lineno=58) failed.
Traceback (most recent call last):
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\aiohttp\connector.py", line 1043, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\sslproto.py", line 574, in _on_handshake_complete
    raise handshake_exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\sslproto.py", line 556, in _do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:992)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\nonebot_plugin_steam_info\__init__.py", line 348, in update_parent_info_handle
    info["avatar"] = PILImage.open(BytesIO(await to_image_data(seg)))
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\nonebot_plugin_steam_info\__init__.py", line 112, in to_image_data
    async with session.get(image.url) as resp:
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\aiohttp\client.py", line 1344, in __aenter__
    self._resp = await self._coro
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\aiohttp\client.py", line 648, in _request
    conn = await self._connector.connect(
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\aiohttp\connector.py", line 546, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\aiohttp\connector.py", line 954, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\aiohttp\connector.py", line 1313, in _create_direct_connection
    raise last_exc
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\aiohttp\connector.py", line 1282, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\XLZPJ\none2bot\none2bot\.venv\Lib\site-packages\aiohttp\connector.py", line 1047, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host multimedia.nt.qq.com.cn:443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:992)]

**Comment by zhaomaoniu** [comment]
使用的协议端是llob吗

**Comment by nodesire7** [comment]
> 使用的协议端是llob吗

是的

**Comment by 23650** [comment]
遇到了相同的问题qwq，插件无法获取到上传的图片；
刚好看到拉格兰那边有解决方案：https://github.com/LagrangeDev/Lagrange.Core/issues/315

**Comment by zhaomaoniu** [comment]
感谢提供解决方案，我会尽快将其加入到插件中

**Comment by zhaomaoniu** [comment]
请尝试更新到最新版后重试

**Comment by 23650** [comment]
> 请尝试更新到最新版后重试

已尝试，最新版可正常获取图片并设置群信息，辛苦
