### ISSUE TITLE
启动机器人时报错

### ISSUE THREAD

**Issue by Zaceee-afk** [zhaomaoniu/nonebot-plugin-steam-info#20]
日志如下
09-20 18:16:50 [ERROR] nonebot | Failed to import "nonebot_plugin_steam_info"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\qq bot\bot_008\bot.py", line 14, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\Desktop\qq bot\bot_008\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\qq bot\bot_008\.venv\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\qq bot\bot_008\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\qq bot\bot_008\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\qq bot\bot_008\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Administrator\Desktop\qq bot\bot_008\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\qq bot\bot_008\.venv\Lib\site-packages\nonebot_plugin_steam_info\__init__.py", line 81, in <module>
    steam_info_data = SteamInfoData(steam_info_data_path)
  File "C:\Users\Administrator\Desktop\qq bot\bot_008\.venv\Lib\site-packages\nonebot_plugin_steam_info\data_source.py", line 90, in __init__
    self.content = json.loads(save_path.read_text("utf-8"))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by zhaomaoniu** [comment]
请尝试进入 C:\Users\Administrator\AppData\Local\nonebot2\nonebot_plugin_steam_info  删除 steam_info.json 后重启 Bot
