### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Sevenyine** [zhaomaoniu/nonebot-plugin-steam-info#22]
在更新完最新版本后，使用 `.steaminfo @人` 时出现报错。（似乎是从没有这个功能更新到这个功能之后然后就这样了）

日志：
```
10-07 13:06:16 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_steam_info, lineno=72) running complete
10-07 13:06:16 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_steam_info, lineno=72) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\nonebot_plugin_steam_info\__init__.py", line 356, in info_handle
    player_data = await get_user_data(steam_id, cache_path, config.proxy)
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\nonebot_plugin_steam_info\steam.py", line 196, in get_user_data
    re.search(r"最后运行日期：(.*) 日", play_time_text).group(1).strip() + " 日"
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by zhaomaoniu** [comment]
能否提供一下出现这个错误的用户的steam id？我也遇到了此问题，但无法复现

**Comment by Sevenyine** [comment]
> 能否提供一下出现这个错误的用户的steam id？我也遇到了此问题，但无法复现

现在我再获取，后台出现的报错变成：
`10-07 14:21:24 [ERROR] nonebot_plugin_steam_info | Failed to get user data: `
然后返回的图片是这样（这个就是之前报错的那个steam id 但是吃个饭回来也无法复现了）TT
![D381A8DB7955DE976816FD1FA8A28F6E](https://github.com/user-attachments/assets/d90d0380-4656-4075-b4b9-7cc3e2e5b376)

**Comment by zhaomaoniu** [comment]
感谢提供信息！steam id是可以根据好友代码计算的，我debug一下

**Comment by Sevenyine** [comment]
> 感谢提供信息！steam id是可以根据好友代码计算的，我debug一下

主要是就算是这个之前报错的id我这边也没法复现了 不如说是个新的bug（笑死）

**Comment by zhaomaoniu** [comment]
> `10-07 14:21:24 [ERROR] nonebot_plugin_steam_info | Failed to get user data: `

这个看起来像网络问题，能稳定复现吗？

**Comment by zhaomaoniu** [comment]
我在 [v1.3.2](https://github.com/zhaomaoniu/nonebot-plugin-steam-info/releases/tag/v1.3.2) 中修复了此问题，更新后即可解决

**Comment by Sevenyine** [comment]
> > `10-07 14:21:24 [ERROR] nonebot_plugin_steam_info | Failed to get user data: `
> 
> 这个看起来像网络问题，能稳定复现吗？

这个问题确实是代理的问题（）之前没配置
谢谢了！
