### ISSUE TITLE
获取不了steam主页信息

### ISSUE THREAD

**Issue by FianlEnd** [zhaomaoniu/nonebot-plugin-steam-info#28]
11-16 17:14:08 [ERROR] nonebot_plugin_steam_info | Failed to get user data:

**Comment by zhaomaoniu** [comment]
请提供完整报错信息

**Comment by FianlEnd** [comment]
Running Matcher(type='message', module=nonebot_plugin_steam_info, lineno=72) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/QQ_Project/True_QQ_BOT/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "/root/QQ_Project/True_QQ_BOT/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 188, in run
    uvicorn.run(
  File "/root/QQ_Project/True_QQ_BOT/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/QQ_Project/True_QQ_BOT/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/QQ_Project/True_QQ_BOT/.venv/lib/python3.10/site-packages/nonebot/utils.py", line 254, in run_coro_with_shield
    return await coro
  File "/root/QQ_Project/True_QQ_BOT/.venv/lib/python3.10/site-packages/nonebot/message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "/root/QQ_Project/True_QQ_BOT/.venv/lib/python3.10/site-packages/nonebot/message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/QQ_Project/True_QQ_BOT/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/QQ_Project/True_QQ_BOT/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 837, in simple_run
    await handler(
  File "/root/QQ_Project/True_QQ_BOT/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/QQ_Project/True_QQ_BOT/.venv/lib/python3.10/site-packages/nonebot_plugin_steam_info/__init__.py", line 339, in info_handle
    steam_id = int(arg.extract_plain_text().strip())
ValueError: invalid literal for int() with base 10: '@ELEVEN-ST'

**Comment by FianlEnd** [comment]
1-16 17:23:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_plus_one.handler, lineno=8)
11-16 17:23:45 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_plus_one.handler, lineno=8)
11-16 17:23:45 [DEBUG] nonebot | Running handler Dependent(call=plush_handler)
11-16 17:23:45 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_plus_one.handler, lineno=8) running complete
11-16 17:23:45 [DEBUG] nonebot | Checking for matchers in priority 5...
11-16 17:23:45 [DEBUG] nonebot | Checking for matchers in priority 8...
11-16 17:23:45 [DEBUG] nonebot | Checking for matchers in priority 10...
11-16 17:23:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_steam_info, lineno=72)
11-16 17:23:45 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_steam_info, lineno=72)
11-16 17:23:45 [DEBUG] nonebot | Running handler Dependent(call=info_handle)
11-16 17:23:50 [ERROR] nonebot_plugin_steam_info | Failed to get user data: //报错
11-16 17:23:51 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
11-16 17:23:52 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_steam_info, lineno=72) running complete
11-16 17:23:52 [DEBUG] nonebot | Checking for matchers in priority 11...
11-16 17:23:52 [DEBUG] nonebot | Checking for matchers in priority 12...
11-16 17:23:52 [DEBUG] nonebot | Checking for matchers in priority 13...
11-16 17:23:52 [DEBUG] nonebot | Checking for matchers in priority 27...
11-16 17:23:52 [DEBUG] nonebot | Checking for matchers in priority 100...
11-16 17:23:52 [DEBUG] nonebot | Checking for matchers completed

**Comment by FianlEnd** [comment]
然后图片里信息只有好友代码，其他主页信息都没有

**Comment by zhaomaoniu** [comment]
请检查 Bot 所处的网络环境是否能连接 Steam 官网。如果不能，请配置代理

**Comment by FianlEnd** [comment]
👌

**Comment by zhaomaoniu** [comment]
请问问题是否得到解决？

**Comment by FianlEnd** [comment]
麻烦问一下应该怎么设置代理🤔

**Comment by zhaomaoniu** [comment]
在 Bot 根目录下的 .env 文件中写入 “PROXY=…” 即可。省略号部分是代理地址，格式通常为 “协议://用户名:密码@主机:端口”。如果你使用 Clash for Windows，它的默认端口是7890，那就应该在 .env 文件中写入 “PROXY=http://127.0.0.1:7890”

**Comment by FianlEnd** [comment]
我是在linux服务器上部署的有没有什么代理设置方法😎

**Comment by FianlEnd** [comment]
要是windows本地解决网络问题倒简单

**Comment by zhaomaoniu** [comment]
Linux 上也有代理方案，你可以自行搜索。

关键词：Linux、代理
